#!/usr/bin/env bash

enable_iptables_rules() {
    # Create forgetproxy chain
    iptables -v -t nat -N FORGETPROXY

    # private ip ranges are not intercepted
    iptables -v -t nat -A FORGETPROXY -d 10.0.0.0/8 -j RETURN;
    iptables -v -t nat -A FORGETPROXY -d 127.0.0.0/8 -j RETURN;
    iptables -v -t nat -A FORGETPROXY -d 169.254.0.0/16 -j RETURN;
    iptables -v -t nat -A FORGETPROXY -d 172.16.0.0/12 -j RETURN;
    iptables -v -t nat -A FORGETPROXY -d 192.168.0.0/16 -j RETURN;
    iptables -v -t nat -A FORGETPROXY -d 224.0.0.0/4 -j RETURN;
    iptables -v -t nat -A FORGETPROXY -d 240.0.0.0/4 -j RETURN;

    # Redirect HTTP port 80 to the http-relay proxy
    # Anything else should be redirected to the http-connect proxy
    iptables -v -t nat -A FORGETPROXY -p tcp --dport 80 -j REDIRECT --to 12345
    iptables -v -t nat -A FORGETPROXY -p tcp            -j REDIRECT --to 12346

    # Redirect traffic from the docker0 interface to the FORGETPROXY chain
    iptables -v -t nat -A PREROUTING -p tcp -i docker0 -j FORGETPROXY
}

disable_iptables_rules() {
    iptables -v -t nat -D PREROUTING -p tcp -i docker0 -j FORGETPROXY
    iptables -v -t nat -F FORGETPROXY
    iptables -v -t nat -X FORGETPROXY
}

append_redsocks_conf() {
  local type=$1
  local ip=$2
  local port=$3
  local local_port=$4
  local user=$5
  local pass=$6
  if [ -z "$type" -o -z "$ip" -o -z "$port" -o -z "$local_port" ] ; then
    echo missing required parameter >&2
    exit 1
  fi
  (cat <<EOF
redsocks {
  type = $type;
  ip = $ip;
  port = $port;
  local_ip = 0.0.0.0;
  local_port = $local_port;
EOF
) >> /tmp/redsocks.conf
if [[ ! -z ${user} ]]; then
  echo "Add user"
  echo "  login = \"$user\";" >> /tmp/redsocks.conf
fi
if [[ ! -z ${pass} ]]; then
  echo "Add password"
  echo "  password = \"$pass\";" >> /tmp/redsocks.conf
fi
echo '}' >> /tmp/redsocks.conf
cat /tmp/redsocks.conf
}

stop() {
    echo "Cleaning iptables"
    disable_iptables_rules
    pkill -9 redsocks
}

interrupted () {
    echo 'Interrupted, cleaning up...'
    trap - INT
    stop
    kill -INT $$
}

run() {
    trap interrupted INT
    trap terminated TERM

    if [ -z "$1" ]; then
        echo "No proxy address set. Exiting"
        exit 1
    fi

    if [ -z "$2" ]; then
        echo "No proxy port set. Exiting"
        exit 1
    fi

    ip=$1
    port=$2
    user=$3
    pass=$4
    append_redsocks_conf "http-relay" $ip $port "12345" $user $pass
    append_redsocks_conf "http-connect" $ip $port "12346" $user $pass

    enable_iptables_rules
    redsocks -c /tmp/redsocks.conf &

    tail -f /dev/null
}


terminated () {
    echo 'Terminated, cleaning up...'
    trap - TERM
    stop
    kill -TERM $$
}

case "$1" in
    stop )  stop ;;
    * )     run "$@" ;;
esac
